config/routes.rb
Rails.application.routes.draw do

  resources :albums, only: %i[index show]

  get 'partiables', to: 'partiable#index'
  get 'partiable/:stage', to: 'partiable#show', as: :partiable

  get 'stage/:slug', to: 'stages#show', as: :stage
  get 'stage/results/:slug', to: 'stages#results', as: :stage_results
  post 'stage/post', to: 'stages#post', as: :stage_post
  post 'stage/post_comments', to: 'stages#post_comments', as: :stage_post_comments
  resources :marks, only: [:create]
  resources :photos, only: %i[new create]
  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
  }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  #get 'contacts' => 'contacts#new', as: :contacts
  #post 'contacts' => 'contacts#create', as: :create_contacts
  #get 'contacts/sent' => 'contacts#sent', as: :contacts_sent

  #get 'search' => 'search#index', as: :search

  #resources :news, only: [:index, :show]

  root to: 'home#index'

  get '*slug' => 'pages#show'
  resources :pages, only: [:show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @stage = Stage.current
    if current_user.role != 'admin'
      unless @stage.markable? current_user
        flash[:errors] = 'Вы не являетесь членом жюри данного этапа'
        redirect_to '/about'
        return
      end
      redirect_to stage_path(@stage)
    end
    @stages      = Stage.closed
    @photographs = @stage.tournament.enabled_photographs
    @juries      = @stage.tournament.juries
    @viewers     = @stage.tournament.viewers
  end
end

app/views/home/_proto_admin.slim
- if @stages.count > 0
  .row: .col-sm-12.text-center: h1 Закрытые туры
  - @stages.each do |stage|
    .row: .col-sm-12.text-center
      = link_to "Результаты тура «#{stage.name}» (дэдлайн #{stage.deadline})", stage_results_path(slug: stage.slug)

- if @stage
  .row: .col-sm-12.text-center: h1 = "Открыт тур «#{@stage.name}»"
  - unless @stage.all_photos_loaded?
    .row: .col-sm-12.text-center = 'Загружены не все фото'
  - @stage.jury_stats.each do |stat|
    .row
      .col = stat[:name]
      .col = "Количество оценок: #{stat[:count]}"
      .col = "Осталось поставить: #{stat[:rest]}"
  .row: .col-sm-12.text-center = "Дедлайн: #{@stage.deadline}"
  - unless @stage.all_photos_loaded?
    .row: .col-sm-12.text-center
      = link_to 'Загрузить фото', new_photo_path(stage: @stage.slug)
    .row: .col-sm-12.text-center
      = link_to 'Загрузить альбом VK', albums_path

app/views/home/index.slim
- if current_user.role == 'admin'
  = render 'proto_admin'



.row
  .col-sm-4
    .row: .col-sm-12.text-center: h1 Фотографы
    - @photographs.each do |photograph|
      .card: .row: .col-sm-12.text-center = photograph.name
  .col-sm-4
    .row: .col-sm-12.text-center: h1 Члены жюри
    - @juries.each do |jury|
      .card: .row: .col-sm-12.text-center = jury.name
  .col-sm-4
    .row: .col-sm-12.text-center: h1 Совет зрителей
    - @viewers.each do |viewer|
      .card: .row: .col-sm-12.text-center = viewer.name