config/routes.rb
Rails.application.routes.draw do

  resources :albums, only: %i[index show]

  get 'partiables', to: 'partiable#index'
  get 'partiable/:stage', to: 'partiable#show', as: :partiable

  get 'stage/:slug', to: 'stages#show', as: :stage
  get 'stage/results/:slug', to: 'stages#results', as: :stage_results
  post 'stage/post', to: 'stages#post', as: :stage_post
  post 'stage/post_comments', to: 'stages#post_comments', as: :stage_post_comments
  resources :marks, only: [:create]
  resources :photos, only: %i[new create]
  devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
  }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  #get 'contacts' => 'contacts#new', as: :contacts
  #post 'contacts' => 'contacts#create', as: :create_contacts
  #get 'contacts/sent' => 'contacts#sent', as: :contacts_sent

  #get 'search' => 'search#index', as: :search

  #resources :news, only: [:index, :show]

  root to: 'home#index'

  get '*slug' => 'pages#show'
  resources :pages, only: [:show]
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  include Vkontakt
  before_action :init_vk_cli

  def index
    @albums = @vk.photos.get_albums(owner_id: @gid, need_covers: true)
  end

  def show
    @stage = Stage.preload(:photos).current
    @photos = @vk.photos.get(owner_id: @gid, album_id: params[:id], photo_sizes: 1)
  end
end

app/views/albums/index.slim
.row: .col-sm-12.text-center: h1 Список альбомов группы
.row: .col-sm-12.text-center
  - @albums.each do |album|
    .card: .card-block
      = link_to album_path(album[:aid]) do
        .row: .col-sm-12.text-center
          = image_tag album[:thumb_src], class: 'img-fluid'
        .row: .col-sm-12.text-center = album.title

app/views/albums/show.slim
.row: .col-sm-12.text-center: h1 = "Этап «#{@stage.name}»"
- @photos.each do |photo|
  .card: .card-block
    .row: .col-sm-12.text-center
      - url = photo.sizes.max_by(&:width).src
      = link_to url, target: '_blank' do
        = image_tag url, class: 'img-fluid'
    /- user = @users.find{|u| u.uid == photo.user_id.to_s}
    /- if user
      /.row: .col-sm-12.text-center
        /= user.name
    .row: .col-sm-12.text-center
      button.btn.btn-success.add-photo-button data-src="#{url}" data-stage="#{@stage.slug}"
        |Добавить это фото